version: '3.8'

services:
  vault:
    image: vault:1.13.3
    container_name: vault-server
    ports:
      - "8205:8205"
    environment:
      - VAULT_DEV_ROOT_TOKEN_ID=myroot
      - VAULT_DEV_LISTEN_ADDRESS=0.0.0.0:8205
    cap_add:
      - IPC_LOCK
    volumes:
      - ./vault/config.hcl:/vault/config/config.hcl
      - ./vault/policies:/vault/policies
    networks:
      - lab-network

  vulnerable-app:
    build: ./app
    container_name: vulnerable-app
    ports:
      - "3000:3000"
    environment:
      - VAULT_ADDR=http://vault:8205
      - VAULT_TOKEN=myroot
    depends_on:
      - vault
    networks:
      - lab-network

  owasp-zap:
    image: zaproxy/zap-stable
    volumes:
      - ./reports:/zap/wrk
    container_name: zap-scanner
    ports:
      - "8080:8080"
    command: zap-webswing.sh
    networks:
      - lab-network

networks:
  lab-network:
    driver: bridge